# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1


- task: PowerShell@2
  inputs:
    filePath: '.\install.depend.ps1'
    pwsh: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  inputs:
    filePath: '.\build.ps1'
    pwsh: true
    workingDirectory: '$(System.DefaultWorkingDirectory)'